frontier:
  we: 1.0
  wg: 1.0
  wf: 1.0
  wc: 1.0
  candidate_dphi: 0.2617993875  # 15 * pi / 180
  candidate_rnum: 10
  candidate_rmin: 0.0
  candidate_rmax: 2.5
  feature_sample_dphi: 0.2617993875  # 15 * pi / 180
  z_sample_max_length: 0.5
  z_sample_num: 5
  cand_limit_per_cluster: 5

  feature:
    candidate_dphi: 0.174532925  # 10 * pi / 180
    candidate_rnum: 5
    candidate_rmin: 0.5
    candidate_rmax: 6.0
    feature_sample_dphi: 0.174532925  # 10 * pi / 180
    z_sample_max_length: 1.0
    z_sample_num: 5
    cand_limit_per_cluster: 10

  final:
    candidate_dphi: 0.2617993875  # 15 * pi / 180
    candidate_rnum: 4
    candidate_rmin: 0.5
    candidate_rmax: 4.5
    feature_sample_dphi: 0.2617993875  # 15 * pi / 180
    z_sample_max_length: 0.5
    z_sample_num: 3
    cand_limit_per_cluster: 5